### ISSUE TITLE
Crash on game start

### ISSUE THREAD

**Issue by etiennec78** [urfour/ArtemisMC-Fabric#5]
Hello, I tried to install your mod on my Linux pc but it crashed even before showing the Mojang logo.
It seems like your mod is trying to read a document in /null/Artemis but this folder doesn't exist.
I have tried enabling Artemis Web API and Remote Control Brush but none of them helped.
Is it crashing because I'm on Linux or have I missed a step in the config ?

Here is the crash report :
[crash-2023-08-12_18.16.51-client.txt](https://github.com/urfour/ArtemisMC-Fabric/files/12327787/crash-2023-08-12_18.16.51-client.txt)

**Comment by urfour** [comment]
Hi, the error is caused because Linux have no "ProgramData" environment variable as I thought so.
The mod was initially made for Windows so I didn't test it on Linux, but I'll fix it.

Can you verify if there is a webserver.txt file in /usr/share/Artemis? (and check if this folder exist).
If it doesn't, I'll need the folder where this file is stored.

**Comment by etiennec78** [comment]
Thanks for your quick response !
I searched your file in my home folder and it is simply located in $HOME/Artemis/
It's quite unusual for an app to store its data in the home folder but this is how Artemis works on linux 🤷

**Comment by urfour** [comment]
Yeah I think it's the common directory for the local application data, even in Mac OS.
Can you try [this version](https://github.com/urfour/ArtemisMC-Fabric/suites/15055234722/artifacts/859709751) and tell me if it works any better? You only need the normal one, not the sources

**Comment by etiennec78** [comment]
It seems like this version is still containing the following path : null/.local/share/Artemis/webserver.txt
null/.local/share/Artemis/webserver.txt
`java.lang.RuntimeException: java.io.FileNotFoundException: null/.local/share/Artemis/webserver.txt (Aucun fichier ou dossier de ce type)`

It should instead be $HOME/Artemis/webserver.txt

**Comment by urfour** [comment]
Java seems not to find your home directory, which distribution of Linux are you using?

**Comment by etiennec78** [comment]
I'm using Arch

**Comment by urfour** [comment]
Okay, the issue must be solved now, check with [this one](https://github.com/urfour/ArtemisMC-Fabric/suites/15057749772/artifacts/859851182).

**Comment by etiennec78** [comment]
Minecraft launched successfully 👍
But now I'm trying to enable your plugin in Artemis and it fails to install Fabric & the mod (but I have already installed both)
Is there a way to enable your plugin without making it install the mod itself ?

**Comment by urfour** [comment]
I just updated the plugin for Fabric and the mod to be installed in the good directory, you can check it out ([link here](https://github.com/urfour/ArtemisMC-Plugin/releases/download/1.1.1.1/ArtemisMC-Plugin.zip))

**Comment by etiennec78** [comment]
When I try to install your plugin into Artemis, I get this message :
![Screenshot_20230813_234112](https://github.com/urfour/ArtemisMC-Fabric/assets/59794011/1fad15be-f6d8-42e8-8ffb-b55b2f57a946)

When I press Install, the window freezes and nothing happens. I'm using PrismLauncher. I don't know if your plugin checks if the mod is in %appdata%/.minecraft/mods but this is not my case.
Is there a way to skip this automatic fabric & mod installation ?

By the way, sorry for all of these requests but I would really like to make your project work on my pc

**Comment by urfour** [comment]
[ArtemisMC-Plugin.zip](https://github.com/urfour/ArtemisMC-Fabric/files/12330554/ArtemisMC-Plugin.zip)

**Comment by etiennec78** [comment]
Everything works now 👍
Thanks for your time taken to make it work on Linux !
Your mod is very complete, I can't wait to see what animations people will be able to make with it when the workshop releases.

**Comment by urfour** [comment]
No problem! Don't hesitate to tell me if there are some features that would be interesting to be added in the [plugin repo](https://github.com/urfour/ArtemisMC-Plugin)!
